<font size=+2.5><b>Name: Aditi Patil 
    Roll no: 7</b></font>
    
    

Numpy stands for numerical python and is a library in python that adds the functionality of large
multi-dimensional arrays and matrices. It works as a building block for all the libraries in pydata
ecosystem. Numpy is one of the most useful tools for a data scientist that uses python. It can
handle large-size data efficiently. One of the biggest reasons to use NumPy is its arrays and multiple
scientific functions to work with arrays.
List of functions explained:

In [2]:
import numpy as np

<font size=+1.5><b>1. numpy.cumsum</b></font>

This function returns the cumulative sum of the elements along a given axis. It returns a new array holding the result is returned unless out is specified, in which case a reference to out is returned. The result has the same size as a, and the same shape as a if axis is not None or a is a 1-d array.


In [19]:
#Example 1
a=np.array([[1,2,3], [4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [6]:
#Example 2
np.cumsum(a,axis=0) 
# This sums over the above rows of each of the columns and returns the sum 

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [7]:
np.cumsum(a,axis=1) 
#This sums over the previous columns of each of the rows and retuns the sum

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [9]:
#However, cumsum(b)[-1] may not be equal to sum(b)
#This is illustrated in the example below

In [16]:
#Example 3
b = np.array([1, 2e-9, 3e-9] * 1000000)
c1=b.cumsum()[-1]
c2=b.sum()
print(c1)
print(c2)

#As we can see they both have a very small difference

1000000.0050045159
1000000.0050000029


<font size=+1.5><b>2. numpy.linalg.det</b></font>

This function is used to compute the determinant of an array.
It takes an array as an input and returns the determinant of that particular array.
The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:

In [18]:
#Example 1
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

# a=1, b=2, c=3, d=4
#ad-bc = 4-(2*3) = -2

-2.0000000000000004

In [21]:
#Computing determinants for a stack of matrices:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
a.shape

np.linalg.det(a)

array([-2., -3., -8.])

<font size=+1.5><b>3. numpy.promote_types</b></font>

Returns the data type with the smallest size and smallest scalar kind to which both type1 and type2 may be safely cast. The returned data type is always considered “canonical”, this mainly means that the promoted dtype will always be in native byte order.

NumPy now supports promotion for more structured dtypes. It will now remove unnecessary padding from a structure dtype and promote included fields individually.
This function is symmetric, but rarely associative.

This function takes two paramenters as datatypes and returns the promoted data type as the output.

In [23]:
#Example 1
np.promote_types('f4', 'f8')
# Hence, here float64 is the smallest size and smallest scalar kind to which both f8 and f4 data types could be cast

dtype('float64')

In [25]:
#Example 2
np.promote_types('i8', 'f4')
# Hence, here float64 is the smallest size and smallest scalar kind to which both i8 and f4 data types could be cast

dtype('float64')

In [28]:
#Example 3
np.promote_types('i4', 'S8')
# Hence, here S11 is the smallest size and smallest scalar kind to which both i4 and S8 data types could be cast

dtype('S11')

In [29]:
#Example 4: An example of a non-associative case

p = np.promote_types
p('S', p('i1', 'u1'))

dtype('S6')

<font size=+1.5><b>4. numpy.rollaxis</b></font>

This function rolls the specified axis backwards, until it lies in a given position.
This function continues to be supported for backward compatibility, but you should prefer moveaxis.
It takes the following parameters: an array, an axis which is to be rolled. The positions of the other axes do not change relative to one another and starting value (start) When start <= axis, the axis is rolled back until it lies in this position. When start > axis, the axis is rolled until it lies before this position. The default, 0, results in a “complete” roll. The following table describes how negative values of start are interpreted:

In [44]:
#Example 1
a = np.ones((3,4,5,6))
b=np.rollaxis(a, 3, 1).shape
print(b)

(3, 6, 4, 5)


In [45]:
#Example 2
np.rollaxis(a, 2).shape

(5, 3, 4, 6)

In [46]:
#Example 3
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4)

<font size=+1.5><b>5. numpy.array_split</b></font>

This function splits an array into multiple sub-arrays.
The only difference between these functions is that array_split allows indices_or_sections to be an integer that does not equally divide the axis. For an array of length l that should be split into n sections, it returns l % n sub-arrays of size l//n + 1 and the rest of size l//n.


In [42]:
#Example 1
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [43]:
#Example 2
x = np.arange(9)
np.array_split(x, 4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]